travel<-read.csv("C:/Users/ATIV/Desktop/travellnsurance.csv",header=TRUE,fileEncoding="UTF-8-BOM")
travel
travel$TravelInsurance<-as.factor(travel$TravelInsurance)
tr1<-nrow(travel)
travel_train<-travel[1:1490,]
travel_test<-travel[1491:tr1,-10]
set.seed(13579)
library(caret)
ih<-createDataPartition(travel_train$TravelInsurance,p=0.8,list=FALSE)
travel_trains<-travel_train[ih,]
travel_valid1<-travel_train[-ih,]
ms_pre<-preProcess(travel_trains[,-10],method=c("range"))
sc_tr_train<-predict(ms_pre,travel_trains)
sc_tr_valid<-predict(ms_pre,travel_valid1)
#svm#
model_svm<-svm(TravelInsurance~.,sc_tr_train,probability=TRUE)
pre_svm<-predict(model_svm,sc_tr_valid,probability=TRUE)
caret::confusionMatrix(pre_svm,travel_valid1$TravelInsurance)
#randomforest#
library(randomForest)
model_random<-randomForest(TravelInsurance~.,sc_tr_train,ntree=300,do.trace=TRUE,probability=TRUE)
pre_random<-predict(model_random,sc_tr_valid,type="response",probability=TRUE)
caret::confusionMatrix(pre_random,sc_tr_valid$TravelInsurance)
set.seed(13579)
md_fit<-randomForest::randomForest(TravelInsurance~.,travel_train,ntree=300,do.trace=TRUE,probability=TRUE)
pred_fit<-predict(md_fit,travel_test,probability=TRUE,type="prob")
print(head(pred_fit))
x_result<-data.frame(c(1:nrow(travel_test)),pred_fit[,2])
colnames(x_result)<-c("index","y_pred")
head(x_result)
library(pROC)
pre_random1<-predict(model_random,sc_tr_valid,type="prob",probability=TRUE)
auc(sc_tr_valid$TravelInsurance,pre_random1[,2])
pre_random
